version: '3'
services:
    my-react-app-live:
        build:
            dockerfile: Dockerfile-live.dev
            context: .
        ports:
            - '2000:3000'
        volumes:
            - /apps/my-react-app/node_modules
            - .:/apps/my-react-app
        